# Generated by Django 2.0.5 on 2018-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.IntegerField(default=0, primary_key='true', serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
